WORD_LIST = ("'39",
"Action This Day",
"All Dead, All Dead",
"All God's People",
"Another One Bites the Dust",
"Arboria (Planet of the Tree Men)",
"Back Chat",
"Battle Theme",
"Bicycle Race",
"Bijou",
"Blurred Vision",
"Body Language",
"Bohemian Rhapsody",
"Breakthru",
"Brighton Rock",
"Bring Back That Leroy Brown",
"Calling All Girls",
"Chinese Torture",
"Coming Soon",
"Cool Cat",
"Crash Dive On Mingo City",
"Crazy Little Thing Called Love",
"Dancer",
"Dead On Time",
"Dear Friends",
"Death on Two Legs (Dedicated to...)",
"Delilah",
"Dog With A Bone",
"Doing All Right",
"Don't Lose Your Head",
"Don't Stop Me Now",
"Don't Try So Hard",
"Don't Try Suicide",
"A Dozen Red Roses For My Darling",
"Dragon Attack",
"Dreamer's Ball",
"Drowse",
"Escape from the Swamp",
"Execution of Flash",
"Face It Alone",
"The Fairy Feller's Master-Stroke",
"Fat Bottomed Girls",
"Father to Son",
"Feel Like",
"Feelings, Feelings",
"Fight from the Inside",
"Flash's Theme",
"Flash to the Rescue",
"Flash's Theme Reprise (Victory Celebrations)",
"Flick of the Wrist",
"Football Fight",
"Forever",
"Friends Will Be Friends",
"Fun It",
"Funny How Love Is",
"Get Down, Make Love",
"Gimme the Prize (Kurgan's Theme)",
"God Save the Queen",
"Good Company",
"Good Old-Fashioned Lover Boy",
"Great King Rat",
"Hammer to Fall",
"Hang On in There",
"Hangman",
"Headlong",
"Heaven for Everyone",
"The Hero",
"Hijack My Heart",
"The Hitman",
"A Human Body",
"I Can't Live with You",
"I Go Crazy",
"I Guess We're Falling Out",
"I Want It All",
"I Want to Break Free",
"I Was Born to Love You",
"If You Can't Beat Them",
"I'm Going Slightly Mad",
"I'm in Love with My Car",
"In Only Seven Days",
"In the Death Cell (Love Theme Reprise)",
"In the Lap of the Gods",
"In the Lap of the Gods... Revisited",
"In the Space Capsule (The Love Theme)",
"Innuendo",
"The Invisible Man",
"Is This the World We Created...?",
"It's a Beautiful Day",
"It's a Beautiful Day (Reprise)",
"It's a Hard Life",
"It's Late",
"Jealousy",
"Jesus",
"Keep Passing the Open Windows",
"Keep Yourself Alive",
"Khashoggi's Ship",
"Killer Queen",
"A Kind of Magic",
"The Kiss (Aura Resurrects Flash)",
"Las Palabras de Amor (The Words of Love)",
"Lazing on a Sunday Afternoon",
"Leaving Home Ain't Easy",
"Let Me Entertain You",
"Let Me in Your Heart Again",
"Let Me Live",
"Liar",
"Life Is Real (Song For Lennon)",
"Lily of the Valley",
"Long Away",
"The Loser in the End",
"Lost Opportunity",
"Love Kills - The Ballad",
"Love of My Life",
"Machines (or 'Back to Humans')",
"Mad the Swine",
"Made in Heaven",
"Man on the Prowl",
"The March of the Black Queen",
"Marriage of Dale & Ming (And Flash Approaching)",
"The Millionaire Waltz",
"Ming's Theme (In the Court of Ming the Merciless)",
"The Miracle",
"Misfire",
"Modern Times Rock 'n' Roll",
"More of That Jazz",
"Mother Love",
"Mustapha",
"My Baby Does Me",
"My Fairy King",
"My Life Has Been Saved",
"My Melancholy Blues",
"Need Your Loving Tonight",
"Nevermore",
"The Night Comes Down",
"No-One but You (Only the Good Die Young)",
"Now I'm Here",
"Ogre Battle",
"One Vision",
"One Year of Love",
"Pain Is So Close to Pleasure",
"Party",
"Play the Game",
"Polar Bear",
"Princes of the Universe",
"Procession",
"The Prophet's Song",
"Put Out the Fire",
"Radio Ga Ga",
"Rain Must Fall",
"Ride the Wild Wind",
"The Ring (Hypnotic Seduction of Dale)",
"Rock It (Prime Jive)",
"Sail Away, Sweet Sister",
"Save Me",
"Scandal",
"Seaside Rendezvous",
"See What a Fool I've Been",
"Seven Seas of Rhye",
"She Makes Me (Stormtrooper in Stilettoes)",
"Sheer Heart Attack",
"Silver Salmon",
"The Show Must Go On",
"Sleeping on the Sidewalk",
"Some Day, One Day",
"Somebody to Love",
"Son And Daughter",
"Soul Brother",
"Spread Your Wings",
"Staying Power",
"Stealin'",
"Stone Cold Crazy ",
"Sweet Lady ",
"Tear It Up",
"Tenement Funster",
"Teo Torriatte (Let Us Cling Together)",
"Thank God It's Christmas",
"There Must Be More to Life Than This",
"These Are the Days of Our Lives",
"Tie Your Mother Down",
"Too Much Love Will Kill You",
"Untitled",
"Under Pressure",
"Vultan's Theme (Attack of the Hawk Men)",
"Was It All Worth It",
"Water",
"We Are the Champions",
"We Will Rock You",
"When Love Breaks Up",
"The Wedding March ",
"White Man",
"White Queen (As It Began)",
"Who Needs You",
"Who Wants to Live Forever",
"A Winter's Tale ",
"Yeah",
"You And I",
"You Don't Fool Me",
"You Know You Belong to Me",
"You Take My Breath Away",
"You're My Best Friend")